spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Qq5203728
    url: jdbc:mysql://119.27.185.124/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell