spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Qq5203728
    url: jdbc:mysql://172.22.12.69/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true